version: "3"
services:
  app:
    container_name: parkoscope
    restart: always
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"